# Eis a calamitosa situação previdenciária dos estados brasileiros

## Objetivos

* Fazer um analises da situação Previdenciaria dos Estados Brasileros.
* Utilizar a ferramenta de python pandas para a transformação e analises dos dados.
* Ler arquivos de excel com pandas.
* fazer plots de graficos com pandas.

In [78]:
import pandas as pd

In [79]:
pd.ExcelFile

pandas.io.excel._base.ExcelFile

In [80]:
excel_file= pd.ExcelFile('Input/Financas_Estaduais.xlsx')

In [210]:
dir(excel_file)

['_ODFReader',
 '_OpenpyxlReader',
 '_XlrdReader',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__fspath__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_engines',
 '_io',
 '_reader',
 'book',
 'close',
 'engine',
 'io',
 'parse',
 'sheet_names']

In [211]:
excel_file.sheet_names

['Info',
 'TOTAL',
 'Demografia_Estadual',
 'RJ',
 'SP',
 'MG',
 'ES',
 'RS',
 'SC',
 'PR',
 'MS',
 'MT',
 'GO',
 'DF',
 'TO',
 'PA',
 'AP',
 'RR',
 'RO',
 'AM',
 'AC',
 'BA',
 'RN',
 'AL',
 'PB',
 'CE',
 'PE',
 'PI',
 'MA',
 'SE',
 'DTP',
 'Endividamento']

In [212]:
sheet_names_per_state=[sheet_name for sheet_name in excel_file.sheet_names if len(sheet_name)==2 ]
sheet_names_per_state

['RJ',
 'SP',
 'MG',
 'ES',
 'RS',
 'SC',
 'PR',
 'MS',
 'MT',
 'GO',
 'DF',
 'TO',
 'PA',
 'AP',
 'RR',
 'RO',
 'AM',
 'AC',
 'BA',
 'RN',
 'AL',
 'PB',
 'CE',
 'PE',
 'PI',
 'MA',
 'SE']

In [213]:
df_RJ=excel_file.parse(
    sheet_names_per_state[0],
    usecols='B:M')
df_RJ.T

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
Unnamed: 1,"Unidade: R$ milhões, a preços correntes",Rio de Janeiro,Receita Bruta,Receita Corrente,Tributária,ICMS,IPVA,ITCD,IRRF,Outras,...,d/q Aposentadorias/ Inativos,d/q Reformas/ Inativos,d/q Pensões/ Inativos,d/q Demais/ Inativos,Civil/ Inativos,Militar/ Inativos,"Resultado Previdenciário (R$ milhões, a preços...",Déficit Previdenciário/ Rec. Corrente Própria,Despesa de Capital/ Rec. Corrente Própria,Resultado Primário/ Rec. Corrente Própria
Unnamed: 2,NaN,2008,41300.2,41047.3,22920.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,4.76098,8.78422
Unnamed: 3,NaN,2009,39727.4,39100.5,24884.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,7.86034,-0.0888004
Unnamed: 4,NaN,2010,47316,46563.9,29086.6,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,12.3975,-0.319216
Unnamed: 5,NaN,2011,53416,52464.1,32555.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,10.5043,2.01315
Unnamed: 6,NaN,2012,55583,55059.7,35141.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,11.0806,-5.40473
Unnamed: 7,NaN,2013,58526.2,58046.8,35685.9,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,13.1004,-12.1995
Unnamed: 8,NaN,2014,58046.9,57708.9,37403.2,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,14.7828,-17.9581
Unnamed: 9,NaN,2015,50971.1,50590.5,29071.7,19189.9,919.719,679.925,2988.13,5294.06,...,52.9519,20.0966,22.1978,4.75372,72.3723,22.874,-878.058,-1.94246,14.6469,-8.02499
Unnamed: 10,NaN,2016,45766.7,45708.4,30547.8,18659.9,1121.33,1112.53,3173.28,6480.76,...,47.7271,19.5758,20.3363,12.3608,65.0733,22.5659,-11346,-30.7943,6.85651,-16.1946
Unnamed: 11,NaN,2017,52628.2,51930.6,32380,19327.8,1142.64,959.647,3831.32,7118.64,...,36.8444,18.0316,17.2545,27.8695,50.2757,21.8548,-10714.6,-23.2043,2.16844,-12.9183
Unnamed: 12,NaN,2018/08,41576.9,39669.3,23932,17780.7,1130.25,609.014,2412.22,1999.76,...,39.454,20.5969,18.9216,21.0275,55.427,23.5454,-749.151,-2.09959,1.22081,21.2483

In [214]:
df_RJ=df_RJ.T
df_RJ

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
Unnamed: 1,"Unidade: R$ milhões, a preços correntes",Rio de Janeiro,Receita Bruta,Receita Corrente,Tributária,ICMS,IPVA,ITCD,IRRF,Outras,...,d/q Aposentadorias/ Inativos,d/q Reformas/ Inativos,d/q Pensões/ Inativos,d/q Demais/ Inativos,Civil/ Inativos,Militar/ Inativos,"Resultado Previdenciário (R$ milhões, a preços...",Déficit Previdenciário/ Rec. Corrente Própria,Despesa de Capital/ Rec. Corrente Própria,Resultado Primário/ Rec. Corrente Própria
Unnamed: 2,NaN,2008,41300.2,41047.3,22920.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,4.76098,8.78422
Unnamed: 3,NaN,2009,39727.4,39100.5,24884.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,7.86034,-0.0888004
Unnamed: 4,NaN,2010,47316,46563.9,29086.6,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,12.3975,-0.319216
Unnamed: 5,NaN,2011,53416,52464.1,32555.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,10.5043,2.01315
Unnamed: 6,NaN,2012,55583,55059.7,35141.7,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,11.0806,-5.40473
Unnamed: 7,NaN,2013,58526.2,58046.8,35685.9,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,13.1004,-12.1995
Unnamed: 8,NaN,2014,58046.9,57708.9,37403.2,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,NaN,0,14.7828,-17.9581
Unnamed: 9,NaN,2015,50971.1,50590.5,29071.7,19189.9,919.719,679.925,2988.13,5294.06,...,52.9519,20.0966,22.1978,4.75372,72.3723,22.874,-878.058,-1.94246,14.6469,-8.02499
Unnamed: 10,NaN,2016,45766.7,45708.4,30547.8,18659.9,1121.33,1112.53,3173.28,6480.76,...,47.7271,19.5758,20.3363,12.3608,65.0733,22.5659,-11346,-30.7943,6.85651,-16.1946
Unnamed: 11,NaN,2017,52628.2,51930.6,32380,19327.8,1142.64,959.647,3831.32,7118.64,...,36.8444,18.0316,17.2545,27.8695,50.2757,21.8548,-10714.6,-23.2043,2.16844,-12.9183
Unnamed: 12,NaN,2018/08,41576.9,39669.3,23932,17780.7,1130.25,609.014,2412.22,1999.76,...,39.454,20.5969,18.9216,21.0275,55.427,23.5454,-749.151,-2.09959,1.22081,21.2483

In [215]:
df_RJ.reset_index(inplace=True,drop=True)

In [216]:
df_RJ=df_RJ.drop(labels=[0],axis=1)

In [217]:
df_RJ.columns=df_RJ.iloc[0]
df_RJ=df_RJ.drop(labels=[0],axis=0)
df_RJ=df_RJ.dropna(axis=1,how='all')

In [225]:
names=df_RJ.columns.to_list()
names[0]='Ano'
names[names.index('Despesa Total¹')] = 'Despesa Total'
df_RJ.columns=names

In [226]:
df_RJ['estado']='RJ'

In [257]:
def get_financials_of_state_from_excel(excel,state):
    df=excel_file.parse(state,usecols='B:M')
    df=df.T
    df.reset_index(inplace=True,drop=True)
    df=df.drop(labels=[0],axis=1)
    df.columns=df.iloc[0]
    df=df.drop(labels=[0],axis=0)
    df=df.dropna(axis=1,how='all')
    names=df.columns.to_list()
    names[0]='Ano'
    names[names.index('Despesa Total¹')] = 'Despesa Total'
    df.columns=names
    df['estado']=state
    return df

df_RJ=get_financials_of_state_from_excel(excel_file,'MS')
df_RJ.T

,1,2,3,4,5,6,7,8,9,10,11
Ano,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018/08
Receita Bruta,6397.51,6433.24,7101.53,8186.59,8920.38,9846.14,10965.2,14504.2,11530.5,12489,8106.19
Receita Corrente,6170.63,6219.22,6709.1,7738.63,8480.44,9278.83,10388.5,12556.6,10925.4,11746.4,7619.28
Tributária,4047.17,3991.13,4380.04,5107.17,5514.05,6174.53,6892.05,7172.78,5540.37,5983.91,4463.09
ICMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5883.74,4252.58,4521.58,3365.24
IPVA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,314.724,197.766,201.409,216.808
ITCD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.8002,132.134,98.2015,87.9303
IRRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,592.049,676.262,887.255,613.073
Outras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,289.473,281.634,275.46,180.044
Transferências,1495.62,1612.48,1666.5,1878.75,2124.66,2100.35,2331.64,2376.53,3052.6,3052.24,2107.37
FPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,813.928,967.197,913.633,658.571
Outras (inclusive Fundeb),NaN,NaN,NaN,NaN,NaN,NaN,NaN,1562.6,2085.41,2138.6,1448.8
Demais Correntes,627.835,615.606,662.556,752.719,841.73,1003.95,1164.84,3007.24,2332.45,2710.26,1048.82
Receita de Capital,226.885,214.024,392.431,447.962,439.936,567.315,576.721,1947.62,605.086,742.598,486.906
Despesa Total,5327.3,5919.93,6845.96,7812.2,8322.43,9480.23,11035.3,12444.9,11456.5,12963.8,7307.35
Despesa Corrente,4918.89,5458.31,6023.63,6830.5,7544.54,8436.56,9343.32,11953.3,10686.9,12000.8,6666.66
Pessoal e Encargos,1877.17,2100.97,2424.01,2693.44,4241.38,4662.34,5154.25,6825.06,7532.81,8695.74,4904.59
Ativos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4860.34,5188.96,5868.75,3045.92
Inativos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1964.72,2343.85,2826.99,1858.67
d/q Aposentadorias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1384.46,1659.26,2028.18,1333.6
d/q Reformas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275.567,309.312,392.298,263.033
d/q Pensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270.072,326.15,381.346,241.475
d/q Demais,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.62,49.1271,25.1647,20.5638
Civil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1632.61,1956.6,2366.68,1549.47
Militar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.734,355.202,450.128,299.189
Outras Despesas Correntes,2861.06,3174.67,3435.17,3946.71,3088.52,3561.36,3978.09,5128.27,3154.07,3305.07,1762.07
Transf. Constitucionais e Legais,1155.47,1121.92,1258.99,1477.78,1593.92,1786.83,1946.7,1998.59,175,171,112
Demais Despesas Correntes,1705.59,2052.75,2176.18,2468.93,1494.6,1774.53,2031.4,3129.68,2979.07,3134.07,1650.07
Despesa de Capital,408.411,461.624,822.328,981.696,777.886,1043.67,1692,491.596,769.578,962.963,640.688
Investimentos,394.743,429.837,811.83,979.755,765.881,1042.29,1647.53,491.596,762.618,962.96,640.688
Inversões Financeiras,13.6679,31.7865,10.498,1.94151,12.0046,1.37121,44.4686,0.00013076,6.96,0.00276,0
Resultado Primário,1070.21,513.31,255.571,374.394,597.95,365.91,-70.0784,2059.26,74.0498,-474.772,798.842
Receita Corrente Própria/ Receita Bruta,73.0754,71.6083,71.0072,71.579,71.2502,72.9065,73.4766,70.1869,68.2782,69.6146,67.9963
Receita de Transferências/ Receita Bruta,23.3782,25.0648,23.4668,22.9491,23.818,21.3317,21.2639,16.3851,26.4741,24.4394,25.9971
Receita de Capital/ Receita Bruta,3.54646,3.32685,5.52601,5.4719,4.93181,5.7618,5.25953,13.428,5.2477,5.94602,6.00659
Pessoal/ Despesa Total,35.2368,35.4897,35.4078,34.4774,50.9633,49.1796,46.7069,54.8421,65.7516,67.0772,67.1187
Pessoal/ Despesa Total ex-Transf.,44.9963,43.7883,43.3867,42.5207,63.036,60.6018,56.711,65.3345,66.7716,67.9739,68.1634
Ativo/ Pessoal e Encargos,0,0,0,0,0,0,0,71.2131,68.8848,67.49,62.1035
Inativo/ Pessoal e Encargos,0,0,0,0,0,0,0,28.7869,31.1152,32.51,37.8965
d/q Aposentadorias/ Inativos,-,-,-,-,-,-,-,70.4661,70.792,71.7435,71.7501
d/q Reformas/ Inativos,-,-,-,-,-,-,-,14.0257,13.1968,13.8769,14.1517
d/q Pensões/ Inativos,-,-,-,-,-,-,-,13.7461,13.9152,13.4895,12.9918
d/q Demais/ Inativos,-,-,-,-,-,-,-,1.76208,2.096,0.89016,1.10637
Civil/ Inativos,-,-,-,-,-,-,-,83.0962,83.4783,83.7173,83.3643
Militar/ Inativos,-,-,-,-,-,-,-,16.0702,15.1547,15.9225,16.0969
"Resultado Previdenciário (R$ milhões, a preços correntes)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1127.01,-1171.35,-859.749,-424.867
Déficit Previdenciário/ Rec. Corrente Própria,0,0,0,0,0,0,0,-11.0708,-14.8784,-9.8888,-7.70816
Despesa de Capital/ Rec. Corrente Própria,8.73605,10.0206,16.3076,16.7528,12.239,14.5388,21.0007,4.82902,9.77513,11.076,11.6237
Resultado Primário/ Rec. Corrente Própria,22.8922,11.1426,5.06824,6.38911,9.40797,5.09733,-0.869794,20.2284,0.940575,-5.46082,14.493
estado,MS,MS,MS,MS,MS,MS,MS,MS,MS,MS,MS

In [259]:
def get_financial_per_state_from_excel(excel):
    states=[sheet_name for sheet_name in excel.sheet_names if len(sheet_name)==2 ]
    df=None
    for state in states :
        df_aux=get_financials_of_state_from_excel(excel,state)
        if not (df is None):
            df=df.append(df_aux, ignore_index=True)
        else:
            df=df_aux
    return df


df=get_financial_per_state_from_excel(excel_file)
df.plot()

ModuleNotFoundError: No module named 'matplotlib'

,Ano,Receita Bruta,Receita Corrente,Tributária,ICMS,IPVA,ITCD,IRRF,Outras,Transferências,...,d/q Aposentadorias/ Inativos,d/q Reformas/ Inativos,d/q Pensões/ Inativos,d/q Demais/ Inativos,Civil/ Inativos,Militar/ Inativos,"Resultado Previdenciário (R$ milhões, a preços correntes)",Déficit Previdenciário/ Rec. Corrente Própria,Despesa de Capital/ Rec. Corrente Própria,Resultado Primário/ Rec. Corrente Própria
count,11.0,11.00,11.000000,11.000000,4.000000,4.000000,4.00000,4.000000,4.000000,11.000000,...,11,11,11,11,11,11,4.000000,11.0,11.000000,11.00000
unique,11.0,11.00,11.000000,11.000000,4.000000,4.000000,4.00000,4.000000,4.000000,11.000000,...,5,5,5,5,5,5,4.000000,5.0,11.000000,11.00000
top,2015.0,39727.38,58046.798829,29071.688236,19327.754869,919.719162,959.64721,3831.315632,7118.637265,5743.360195,...,-,-,-,-,-,-,-11345.982253,0.0,14.646928,-17.95806
freq,1.0,1.00,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,...,7,7,7,7,7,7,1.000000,7.0,1.000000,1.00000

In [45]:

df_RJ=df_RJ.drop(labels=[0])
df_RJ=df_RJ.drop(labels=[0])

df_RJ

KeyError: '[0] not found in axis'

In [241]:
a= None

caca